version: "3.8"

services:

  kong:
    build:
      context: ./kong
      dockerfile: Dockerfile
    container_name: kong-gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8005"
      P_VALUE: 50  # This sets the initial traffic distribution
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8005:8005"

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5673:5672"
      - "15673:15672"


  neo4j:
    image: "neo4j:latest"
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - ./neo4j_data:/data
    ports:
      - "7474:7474"
      - "7687:7687"

  dataprocess:
    build:
      context: ./dataprocess
      dockerfile: Dockerfile
    container_name: dataprocess
    ports:
      - "8001:8001"
    # depends_on:
    #   - rabbitmq
    #   - neo4j
    volumes:
      - ./dataprocess:/app/dataprocess


  modelserver:
    build:
      context: ./modelserver
      dockerfile: Dockerfile
    container_name: modelserver
    ports:
      - "8002:8002"
    # depends_on:
    #   - neo4j  
    volumes:
      - ./modelserver:/app/modelserver


  xaiserver:
    build:
      context: ./xaiserver
      dockerfile: Dockerfile
    container_name: xaiserver
    ports:
      - "8003:8003"
    # depends_on:
    #   - neo4j  
    volumes:
      - ./xaiserver:/app/xaiserver


  center_server:
    build:
      context: ./centerserver
      dockerfile: Dockerfile
    container_name: center_server
    ports:
      - "8880:8880"
    volumes:
      - ./centerserver:/app
    depends_on:
      - neo4j
      - kong
      - rabbitmq
      - dataprocess
      - modelserver
      - xaiserver


